### ISSUE TITLE
Forms without modal

### ISSUE THREAD

**Issue by pboisclair** [lcharette/UF_FormGenerator#3]
HI,

It is possible to the Form generator generate without form not in modal.

I'm have to create 6 forms with a lot of field but I want this form directly on the page.
I know I can use the UF Form but with the number of fields it will be very time consuming

Thanks

**Comment by lcharette** [comment]
Of course !  It's all in the [ReadMe](https://github.com/lcharette/UF_FormGenerator#the-controller-part). 

My ConfigManager Sprinkle is using non modal forms ([Here](https://github.com/lcharette/UF_ConfigManager/blob/master/src/Controller/ConfigManagerController.php#L93) and [here](https://github.com/lcharette/UF_ConfigManager/blob/master/templates/pages/ConfigManager.html.twig#L33)).
