### ISSUE TITLE
Horizontal Layout - Alert Display Issue

### ISSUE THREAD

**Issue by JoshNorris** [lcharette/UF_FormGenerator#7]
When an `alert` is used under any other form element is takes up the previous high until the last alert box was used. 

![image](https://user-images.githubusercontent.com/21032800/51081058-e5a74f00-173a-11e9-9d58-49eaa59a18a7.png)

This is due to the floating of the `label` and actual `input type` for each element being generated in this layout and then not clearing the floats of the over-arcing element. By not clearing the parent element of the floating conditions it results in all parents of the input parents having a `0 height`. 

Adding the `clearfix` class when declaring the `form-group has-feedback` for the horizontal layout fixes the issue.

**Comment by lcharette** [comment]
Merged
